declare @BillContractTypeId int = 0

insert BillContractType
(
	Name,
	Description,
	CurrentlyOffered,
	CreateDate)
select 'PAYAGREE',
'Payment Agreement',
1,
GETUTCDATE()

select @BillContractTypeId = SCOPE_IDENTITY()

insert BillContractTypeTemplate
(
	BillContractTypeId,
	ProviderId,
	TemplateName,
	TemplateHeader,
	Template,
	Description,
	CreateDate)
select @BillContractTypeId,
NULL,
'PAYAGREE',
'Payment Agreement',
'<p>Last Updated: September 18th, 2015</p><br>
<p>1. CONTRACTUAL RELATIONSHIP</p>
<p>This WEYI PROVIDER PAYMENT TERMS ("Payment Terms") governs the payment terms between you, a third party interpretation service provider ("YOU", "Provider"), and WEYI, INC and its subsidiaries and affiliates (collectively, "WEYI"). It is supplementary of the WEYI PROVIDER AGREEMENT between YOU and WEYI.</p>
<p>2. THE WEYI PLATFORM</p>
<p>The WEYI Platform is a technology platform that enables clients ("Clients") of WEYI''s mobile applications or websites provided as part of the WEYI Platform (each, an "Application") to get real time interpretation services ("Services") from third party providers of such services, including independent third party interpretation providers under agreement with WEYI or certain of WEYI''s affiliates ("Providers"). YOU ACKNOWLEDGE THAT WEYI DOES NOT PROVIDE INTERPRETATION SERVICES AS AN INTERPRETATION PROVIDER. IT IS UP TO YOU TO DECIDE WHETHER OR NOT TO OFFER AN INTERPRETATION SERVICE TO A CLIENT CONTACTED THROUGH THE WEYI PLATFORM. EACH INTERPRETATION SERVICE PROVIDED BY YOU TO A CLIENT SHALL CONSTITUTE A SEPARATE AGREEMENT BETWEEN THE CLIENT AND YOU.</p>
<p>3. TERMS</p>
<p>YOU AUTHORIZE WEYI TO DECIDE ON YOUR BEHALF WHETHER TO CHARGE A CLIENT AND HOW MUCH TO CHARGE A CLIENT FOR EACH SERVICE DELIVERED BY YOU. YOU AUTHORIZE WEYI TO COLLECT PAYMENT ON YOUR BEHALF FROM A CLIENT WHEN APPLICABLE. WEYI WILL MAKE PAYMENT TO YOU FOR SERVICES DELIVERED BY YOU BASED ON THE MUTUALLY AGREED PAYMENT TERMS. YOU ACKNOWLEGE THAT YOUR PAYMENT TERMS MAYBE DIFFERENT FROM OTHER WEYI PROVIDERS.</p>
<p>The Payment Terms are effective upon YOU being approved by WEYI to provide Services for the Clients and will expire in 90 days. The Payment Terms automatically renew for 90 days at the end of each term unless WEYI notifies YOU by Email and/or Text 10 calendar days before the current expiration date. Either party may terminate this agreement at any time by notification as follows. Providers must notify WEYI of termination of agreement through the email provideragreement@weyimobile.com. WEYI must notify providers of termination of agreement through the provider''s WEYI provider account.</p>
<p>4. PAYMENT</p>
<p>YOU will be paid at hourly rate between US$25 to US$45 per hour for the total Service time YOU provide to the Clients. The exact hourly rate YOU earn is solely determined by WEYI based on various factors, such as the performance rating by the Clients and other market factors. The Service time for a Service starts when the WEYI system confirms YOUR acceptance of a Service request. For each accepted but not confirmed Service, such as when a request is accepted and confirmed by another provider before you, the service time is counted as 1 minute toward YOUR total service time. The Service time stops when the Service is stopped by the Clients, or by WEYI System. The Service time for an accepted and confirmed Service will be the actual minutes (seconds will be rounded up to the closest minute) for a service, or 1 minute, whichever is greater.</p>
<p>YOU are eligible to get payment by Check, ACH, or PayPal once a month. YOU are guaranteed a minimum payment of US$10 per 30 days when YOU have provided no Service during the 30 day period, or when the Payment Terms is terminated by WEYI before the full 30 day period. The total amount per payment is calculated using the hourly rate converted to rate per minute and the total service minutes in the paying period.</p>
<p>The Provider agrees that from time to time they will receive service requests that are “test calls” generated by WEYI''s internal team or prospective users and providers for the purpose of ensuring the integrity and functionality of the WEYI service offering and WEYI platform. "Test calls" will be reimbursed at WEYI''s sole discretion.</p>
<p>5. OTHER PROVISIONS</p>
<p>CHOICE OF LAW.</p>
<p>This Payment Terms are governed by and construed in accordance with the laws of the State of Florida, U.S.A., without giving effect to any conflict of law principles.</p>
<p>CLAIMS OF COPYRIGHT INFRINGEMENT.</p>
<p>Claims of copyright infringement should be sent to WEYI''s designated agent. Please visit WEYI''s web page at <a href="//www.WEYIMobile.com">www.WEYIMobile.com</a> for the designated address and additional information.</p>
<p>NOTICE.</p>
<p>WEYI may give notice by means of a general notice on the WEYI Platform, electronic mail to your email address in your Account， Text to your mobile phone in your Account. Such notice shall be deemed to have been given upon the expiration of 12 hours after sending by email or Text. YOU may give notice to WEYI, with such notice deemed given when received by WEYI, at any time by first class mail or pre-paid post to WEYI, INC, Attn: User Notices - Legal, 12555 Orange Drive, Suite 100B, Davie, FL 33330.</p>
<p>GENERAL.</p>
<p>YOU may not assign this Payment Terms without WEYI''s prior written approval. WEYI may assign this Payment Terms without your consent to: (i) a subsidiary or affiliate; (ii) an acquirer of WEYI''s equity, business or assets; or (iii) a successor by merger. Any purported assignment in violation of this section shall be void. No joint venture, partnership, employment, or agency relationship exists between YOU, WEYI or any Third Party Provider as a result of this Payment Terms or use of the WEYI Platform. If any provision of this Payment Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. WEYI''s failure to enforce any right or provision in this Payment Terms shall not constitute a waiver of such right or provision unless acknowledged and agreed to by WEYI in writing.</p>
',
'',
GETUTCDATE()