
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Leke', N'ALL', N'Lek', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'USD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Afghanis', N'AFN', N'؋', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'ARS', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Guilders', N'AWG', N'ƒ', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'AUD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('New Manats', N'AZN', N'ман', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'BSD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'BBD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rubles', N'BYR', N'p.', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Euro', N'EUR', N'€', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'BZD', N'BZ$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'BMD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Bolivianos', N'BOB', N'$b', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Convertible Marka', N'BAM', N'KM', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pula', N'BWP', N'P', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Leva', N'BGN', N'лв', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Reais', N'BRL', N'R$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'GBP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'BND', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Riels', N'KHR', N'៛', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'CAD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'KYD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'CLP', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Yuan Renminbi', N'CNY', N'¥', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'COP', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Colón', N'CRC', N'₡', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Kuna', N'HRK', N'kn', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'CUP', N'₱', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Koruny', N'CZK', N'Kč', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Kroner', N'DKK', N'kr', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'DOP ', N'RD$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'XCD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'EGP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Colones', N'SVC', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'FKP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'FJD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Cedis', N'GHC', N'¢', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'GIP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Quetzales', N'GTQ', N'Q', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'GGP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'GYD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Lempiras', N'HNL', N'L', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'HKD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Forint', N'HUF', N'Ft', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Kronur', N'ISK', N'kr', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'INR', N'Rp', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupiahs', N'IDR', N'Rp', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rials', N'IRR', N'﷼', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'IMP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('New Shekels', N'ILS', N'₪', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'JMD', N'J$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Yen', N'JPY', N'¥', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'JEP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Tenge', N'KZT', N'лв', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Won', N'KPW', N'₩', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Won', N'KRW', N'₩', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Soms', N'KGS', N'лв', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Kips', N'LAK', N'₭', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Lati', N'LVL', N'Ls', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'LBP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'LRD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Switzerland Francs', N'CHF', N'CHF', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Litai', N'LTL', N'Lt', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Denars', N'MKD', N'ден', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Ringgits', N'MYR', N'RM', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'MUR', N'₨', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'MXN', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Tugriks', N'MNT', N'₮', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Meticais', N'MZN', N'MT', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'NAD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'NPR', N'₨', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Guilders', N'ANG', N'ƒ', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'NZD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Cordobas', N'NIO', N'C$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Nairas', N'NGN', N'₦', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Krone', N'NOK', N'kr', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rials', N'OMR', N'﷼', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'PKR', N'₨', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Balboa', N'PAB', N'B/.', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Guarani', N'PYG', N'Gs', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Nuevos Soles', N'PEN', N'S/.', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'PHP', N'Php', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Zlotych', N'PLN', N'zł', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rials', N'QAR', N'﷼', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('New Lei', N'RON', N'lei', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rubles', N'RUB', N'руб', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'SHP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Riyals', N'SAR', N'﷼', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dinars', N'RSD', N'Дин.', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'SCR', N'₨', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'SGD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'SBD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Shillings', N'SOS', N'S', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rand', N'ZAR', N'R', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rupees', N'LKR', N'₨', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Kronor', N'SEK', N'kr', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'SRD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pounds', N'SYP', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('New Dollars', N'TWD', N'NT$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Baht', N'THB', N'฿', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'TTD', N'TT$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Lira', N'TRY', N'TL', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Liras', N'TRL', N'£', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dollars', N'TVD', N'$', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Hryvnia', N'UAH', N'₴', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Pesos', N'UYU', N'$U', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Sums', N'UZS', N'лв', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Bolivares Fuertes', N'VEF', N'Bs', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Dong', N'VND', N'₫', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Rials', N'YER', N'﷼', 1);
INSERT INTO currency (EnglishName, code, symbol, Available) VALUES ('Zimbabwe Dollars', N'ZWD', N'Z$', 1);